import type { BraData, Question } from "./types";

export const DEFAULT_LADDER = [
  100, 200, 300, 500, 1000, 2000, 4000, 8000, 16000, 32000, 64000, 125000, 250000, 500000,
  1000000,
];

export const uid = () => Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4);

const cats = [
  { id: "c-sindy", name: "Sindy", active: true },
  { id: "c-amigos", name: "Amigos", active: true },
  { id: "c-recuerdos", name: "Recuerdos", active: true },
  { id: "c-cultura", name: "Cultura general", active: true },
  { id: "c-musica", name: "Música", active: true },
  { id: "c-cine", name: "Películas", active: true },
  { id: "c-personales", name: "Preguntas personales", active: true },
  { id: "c-random", name: "Random", active: true },
];

const seed: Omit<Question, "id" | "createdAt">[] = [
  {
    text: "¿Cuál de estas opciones representa mejor a Sindy?",
    answers: ["Puntual hasta el segundo", "Reina del audio de 4 minutos", "Odia el café", "Nunca usa emojis"],
    correct: 1,
    explanation: "Nadie manda audios más épicos que Sindy.",
    categoryId: "c-sindy",
    difficulty: "facil",
    prize: 100,
    timeLimit: null,
    order: 1,
    tags: ["intro"],
    active: true,
  },
  {
    text: "Si Sindy pudiera teletransportarse a un solo lugar, sería…",
    answers: ["La playa", "Un concierto", "La cama", "La oficina"],
    correct: 2,
    explanation: "La cama gana siempre. Siempre.",
    categoryId: "c-personales",
    difficulty: "facil",
    prize: 200,
    timeLimit: null,
    order: 2,
    tags: [],
    active: true,
  },
  {
    text: "¿Qué frase dice Sindy al menos una vez al día?",
    answers: ["“Ya voy saliendo”", "“Hoy sí madrugo”", "“Última copa”", "“Mañana empiezo la dieta”"],
    correct: 0,
    explanation: "“Ya voy saliendo” = todavía está en pijama.",
    categoryId: "c-amigos",
    difficulty: "media",
    prize: 300,
    timeLimit: null,
    order: 3,
    tags: [],
    active: true,
  },
  {
    text: "¿Cuál es el plan perfecto de viernes según el grupo?",
    answers: ["Cine en casa", "Salir a bailar", "Cena y chismes", "Dormir temprano"],
    correct: 2,
    explanation: "La cena es la excusa; el chisme es el plan.",
    categoryId: "c-recuerdos",
    difficulty: "media",
    prize: 500,
    timeLimit: null,
    order: 4,
    tags: [],
    active: true,
  },
  {
    text: "¿Qué planeta del sistema solar tiene el día más largo?",
    answers: ["Marte", "Venus", "Júpiter", "Mercurio"],
    correct: 1,
    explanation: "Un día en Venus dura más que su propio año.",
    categoryId: "c-cultura",
    difficulty: "dificil",
    prize: 1000,
    timeLimit: null,
    order: 5,
    tags: [],
    active: true,
  },
  {
    text: "¿Qué artista popularizó el término “Bichota”?",
    answers: ["Karol G", "Shakira", "Rosalía", "Becky G"],
    correct: 0,
    explanation: "Karol G, obviamente.",
    categoryId: "c-musica",
    difficulty: "facil",
    prize: 2000,
    timeLimit: null,
    order: 6,
    tags: [],
    active: true,
  },
  {
    text: "En “El Padrino”, ¿qué animal aparece en la cama del productor?",
    answers: ["Un perro", "Un caballo", "Un toro", "Un gato"],
    correct: 1,
    explanation: "La cabeza del caballo: la escena más famosa del cine.",
    categoryId: "c-cine",
    difficulty: "media",
    prize: 4000,
    timeLimit: null,
    order: 7,
    tags: [],
    active: true,
  },
  {
    text: "¿Cuál es la primera reacción de Sindy ante una foto mal tomada?",
    answers: ["La publica igual", "Exige repetirla 12 veces", "La borra en silencio", "La convierte en meme"],
    correct: 1,
    explanation: "12 tomas mínimo. Es ley.",
    categoryId: "c-sindy",
    difficulty: "media",
    prize: 8000,
    timeLimit: null,
    order: 8,
    tags: [],
    active: true,
  },
  {
    text: "¿Cuántos huesos tiene aproximadamente el cuerpo humano adulto?",
    answers: ["186", "206", "226", "246"],
    correct: 1,
    explanation: "206 huesos en un adulto.",
    categoryId: "c-cultura",
    difficulty: "dificil",
    prize: 16000,
    timeLimit: null,
    order: 9,
    tags: [],
    active: true,
  },
  {
    text: "¿Qué haría Sindy si se ganara el millón de BRA-YANARIO?",
    answers: ["Invertirlo", "Viajar sin avisar", "Invitar a todos", "Guardarlo bajo el colchón"],
    correct: 1,
    explanation: "Nos enteraríamos por una historia de Instagram desde otro país.",
    categoryId: "c-personales",
    difficulty: "experta",
    prize: 32000,
    timeLimit: null,
    order: 10,
    tags: [],
    active: true,
  },
];

export const defaultData = (): BraData => ({
  categories: cats,
  participants: [
    {
      id: "p-sindy",
      name: "Sindy Marin",
      description: "Primera concursante de la historia de BRA-YANARIO.",
      accent: "#e60023",
      createdAt: new Date().toISOString(),
    },
  ],
  runs: [],
  questions: seed.map((q) => ({ ...q, id: uid(), createdAt: new Date().toISOString() })),
  settings: {
    gameName: "¿QUIÉN QUIERE SER BRA-YANARIO?",
    participantName: "Sindy Marin",
    subtitle: "Edición especial",
    welcomeMessage:
      "Sindy, tienes una misión. Responde correctamente y demuestra cuánto sabes.",
    finalMessage: "El escenario se apaga… pero la leyenda queda.",
    questionCount: 10,
    defaultTime: 30,
    allowRepeat: false,
    showExplanation: true,
    soundEnabled: true,
    volume: 0.5,
    animationsEnabled: true,
    ladder: DEFAULT_LADDER,
    lifelines: [
      { id: "5050", name: "50/50", description: "Elimina dos respuestas incorrectas.", enabled: true },
      { id: "publico", name: "Pregunta al público", description: "Muestra los porcentajes del público.", enabled: true },
      { id: "amigo", name: "Llamar a un amigo", description: "Un amigo te da su opinión.", enabled: true },
    ],
  },
});
